Explicit string argument for privateKey
By passing a Buffer argument, we got `init failed:TypeError: a.replace is not a function`
Update README so that Cloud code integration works as expected.